import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = { title: "Serviços | Educatec" };
const servicos = ["Consultoria educacional", "Gestão e desenvolvimento institucional", "Formação e desenvolvimento", "Eventos esportivos, culturais e educacionais", "Tecnologia e dados"];
const metodo = ["Diagnóstico do problema, do território ou da instituição", "Definição dos objetivos, públicos e resultados esperados", "Concepção técnica e planejamento estratégico", "Modelagem de governança, responsabilidades e instrumentos", "Mobilização dos parceiros e atores envolvidos", "Execução presencial, remota ou híbrida", "Monitoramento por indicadores, reuniões e relatórios", "Avaliação, comunicação dos resultados e prestação de contas"];

export default function Servicos() { return <main className="bg-[#faf8f4] text-slate-800"><section className="mx-auto max-w-7xl px-6 py-16 lg:px-10"><p className="text-sm font-bold uppercase tracking-[.2em] text-amber-700">Serviços</p><h1 className="mt-4 max-w-5xl font-serif text-5xl font-bold text-slate-950 md:text-6xl">Da concepção à execução: soluções que chegam prontas para acontecer.</h1><div className="mt-12 grid gap-6 md:grid-cols-2">{servicos.map((s,i)=><article key={s} className="rounded-3xl bg-white p-7 shadow-sm"><span className="text-sm font-bold text-amber-700">0{i+1}</span><h2 className="mt-3 font-serif text-2xl font-bold">{s}</h2></article>)}</div></section>
  <section className="bg-slate-950 py-16 text-white"><div className="mx-auto grid max-w-7xl gap-8 px-6 md:grid-cols-2 lg:px-10"><figure><div className="relative aspect-[4/3] overflow-hidden rounded-3xl"><Image src="/images/institucional/servicos-articulacao.webp" alt="Ney Campello em evento de articulação institucional" fill className="object-cover" /></div><figcaption className="mt-3 text-sm text-slate-400">Eventos, articulação e relacionamento institucional</figcaption></figure><figure><div className="relative aspect-[4/3] overflow-hidden rounded-3xl"><Image src="/images/institucional/servicos-planejamento.webp" alt="Reunião de planejamento com materiais técnicos" fill className="object-cover" /></div><figcaption className="mt-3 text-sm text-slate-400">Consultoria, diagnóstico e planejamento</figcaption></figure></div></section>
  <section className="mx-auto max-w-5xl px-6 py-16 lg:px-10"><h2 className="font-serif text-3xl font-bold text-slate-950">Projetos esportivos e culturais</h2><p className="mt-5 text-lg leading-8">As ações podem ser desenvolvidas diretamente pela Educatec ou em parceria com governos, confederações, federações, universidades, institutos e empresas especializadas. O escopo de cada participante é definido de acordo com o projeto, desde a concepção até a execução e a prestação de contas.</p><div className="mt-10 rounded-3xl bg-amber-50 p-8"><h3 className="font-serif text-2xl font-bold">Copa Feminina 2027</h3><p className="mt-4 leading-8">Entre as experiências acompanhadas está a proposta de planejamento e preparação para a Copa do Mundo Feminina FIFA 2027 na Bahia, concebida pela Educatec. As atividades vêm sendo desenvolvidas por seu líder empresarial, o professor Ney Campello, por meio de sua atuação como bolsista de um instituto vinculado à Universidade do Paraná.</p></div></section>
  <section className="bg-white py-16"><div className="mx-auto max-w-5xl px-6 lg:px-10"><h2 className="font-serif text-3xl font-bold">Método de trabalho</h2><ol className="mt-8 grid gap-5 md:grid-cols-2">{metodo.map((m,i)=><li key={m} className="flex gap-4 rounded-2xl bg-slate-50 p-5"><span className="font-bold text-amber-700">{i+1}</span><span className="leading-7">{m}</span></li>)}</ol><Link href="/contato" className="mt-10 inline-block rounded-full bg-slate-950 px-7 py-3 font-bold text-white">Solicite uma proposta</Link></div></section></main> }
