import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = { title: "Quem Somos | Educatec" };

export default function QuemSomos() {
  return <main className="bg-[#faf8f4] text-slate-800"><section className="mx-auto grid max-w-7xl gap-12 px-6 py-16 lg:grid-cols-2 lg:items-center lg:px-10"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-amber-700">Quem somos</p><h1 className="mt-4 font-serif text-5xl font-bold text-slate-950 md:text-6xl">Soluções completas em educação, gestão, esporte, cultura e eventos.</h1></div><div className="relative aspect-[4/3] overflow-hidden rounded-3xl"><Image src="/images/institucional/quem-somos-equipe.webp" alt="Ney Jorge Campello e equipe em encontro profissional" fill priority className="object-cover" /></div></section>
  <section className="mx-auto max-w-4xl space-y-6 px-6 pb-16 text-lg leading-8 lg:px-10"><p>A Educatec é uma empresa de planejamento, gestão e consultoria que desenvolve soluções para governos, instituições de ensino, organizações sociais, entidades empresariais e parceiros privados. Sua atuação abrange a concepção, a estruturação, a execução, o monitoramento e a prestação de contas de projetos nas áreas de educação, esporte, cultura, formação profissional, desenvolvimento institucional e eventos.</p><p>A empresa combina experiência em gestão pública, planejamento educacional, articulação de redes, produção de eventos e formação de lideranças. Sua atuação vai além da organização de eventos: a Educatec compreende problemas complexos, cria modelos de atuação, integra instituições e transforma propostas em soluções completas e executáveis.</p><p>A Educatec desenvolve seus projetos por meio da cooperação com órgãos públicos, instituições de ensino, confederações, federações, institutos e empresas especializadas. Em cada trabalho, as responsabilidades e os vínculos institucionais são apresentados com clareza, respeitando o papel efetivamente desempenhado pela empresa, por seus profissionais e por seus parceiros.</p></section>
  <section className="bg-white py-16"><div className="mx-auto grid max-w-7xl gap-6 px-6 md:grid-cols-3 lg:px-10">{[
    ["Propósito", "Transformar necessidades públicas e institucionais em projetos estruturados, executáveis e socialmente relevantes, utilizando educação, esporte, cultura e gestão como instrumentos de desenvolvimento humano e territorial."],
    ["Missão", "Promover educação, esporte e cultura como dimensões integradas do desenvolvimento, oferecendo planejamento, consultoria, formação e execução de projetos capazes de gerar autonomia, desenvolvimento sustentável e formação integral."],
    ["Visão", "Consolidar-se como uma das principais referências da Bahia em consultoria educacional, planejamento institucional e produção de eventos esportivos e culturais."],
  ].map(([t,x]) => <article key={t} className="rounded-3xl bg-slate-50 p-7"><h2 className="font-serif text-2xl font-bold text-slate-950">{t}</h2><p className="mt-4 leading-7 text-slate-600">{x}</p></article>)}</div></section></main>;
}
