import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = { title: "Ney Jorge Campello | Educatec" };

export default function NeyCampello() { return <main className="bg-[#faf8f4] text-slate-800"><section className="mx-auto grid max-w-7xl gap-12 px-6 py-16 lg:grid-cols-[.8fr_1.2fr] lg:items-center lg:px-10"><div className="relative aspect-[4/5] overflow-hidden rounded-3xl"><Image src="/images/ney-campello/ney-campello-retrato-principal.jpg" alt="Ney Jorge Campello" fill priority className="object-cover" /></div><div><p className="text-sm font-bold uppercase tracking-[.2em] text-amber-700">Liderança empresarial</p><h1 className="mt-4 font-serif text-5xl font-bold text-slate-950 md:text-7xl">Ney Jorge Campello</h1><p className="mt-6 text-xl leading-9 text-slate-600">Educador, gestor público e articulador de projetos nas áreas de educação, esporte, cultura e desenvolvimento institucional.</p><p className="mt-6 leading-8">Sua trajetória reúne experiência em planejamento educacional, gestão pública, preparação de grandes eventos e articulação entre governos, instituições de ensino, entidades empresariais e organizações sociais.</p></div></section>
  <section className="bg-white py-16"><div className="mx-auto grid max-w-7xl gap-10 px-6 lg:grid-cols-2 lg:px-10"><div><p className="text-sm font-bold uppercase tracking-widest text-amber-700">Coordenação técnica</p><h2 className="mt-3 font-serif text-3xl font-bold">Planejamento e articulação</h2><p className="mt-5 leading-8 text-slate-600">Reuniões técnicas, coordenação de equipes e construção de soluções com instituições parceiras fazem parte de sua atuação profissional.</p></div><figure><div className="relative aspect-[4/3] overflow-hidden rounded-3xl"><Image src="/images/institucional/ney-reuniao-coordenacao.webp" alt="Ney Campello em reunião de coordenação técnica" fill className="object-cover" /></div><figcaption className="mt-3 text-sm text-slate-500">Reunião de coordenação e articulação técnica</figcaption></figure></div></section>
  <section className="mx-auto max-w-7xl px-6 py-16 lg:px-10"><p className="text-sm font-bold uppercase tracking-widest text-amber-700">Entrevistas e presença na mídia</p><h2 className="mt-3 font-serif text-3xl font-bold">Experiência compartilhada</h2><div className="mt-8 grid gap-6 md:grid-cols-2"><figure><div className="relative aspect-video overflow-hidden rounded-3xl"><Image src="/images/ney-campello/ney-campello-entrevista-tv.png" alt="Ney Campello em entrevista para televisão" fill className="object-cover" /></div><figcaption className="mt-3 text-sm text-slate-500">Entrevista e presença na mídia</figcaption></figure><figure><div className="relative aspect-video overflow-hidden rounded-3xl"><Image src="/images/ney-campello/ney-campello-entrevista-radio.jpg" alt="Ney Campello durante entrevista em rádio" fill className="object-cover" /></div><figcaption className="mt-3 text-sm text-slate-500">Entrevista em rádio</figcaption></figure></div></section>
  <section className="bg-slate-950 py-16 text-white"><div className="mx-auto grid max-w-7xl gap-10 px-6 lg:grid-cols-[.8fr_1.2fr] lg:items-center lg:px-10"><figure><div className="relative aspect-[3/4] overflow-hidden rounded-3xl"><Image src="/images/institucional/ney-via-educacao-poesia.webp" alt="A Via da Educação e da Poesia, de Ney Campello" fill className="object-cover" /></div></figure><div><p className="text-sm font-bold uppercase tracking-widest text-amber-400">Educação, poesia e trajetória intelectual</p><h2 className="mt-4 font-serif text-4xl font-bold">A Via da Educação e da Poesia</h2><p className="mt-6 text-lg leading-8 text-slate-300">A reflexão sobre educação, cultura e poesia integra a produção intelectual de Ney Jorge Campello e sua compreensão da formação humana como processo amplo, conectado ao território e à vida pública.</p></div></div></section></main> }
